name = "compass"
title = "MongoDB Compass"

intersphinx = [
    "https://www.mongodb.com/docs/manual/objects.inv",
    "https://www.mongodb.com/docs/database-tools/objects.inv",
    "https://www.mongodb.com/docs/mongodb-shell/objects.inv",
    "https://www.mongodb.com/docs/atlas/objects.inv"
]

toc_landing_pages = [
    "/install", 
    "/connect",
    "/settings",
    "/settings/config-file",
    "/connect/advanced-connection-options",
    "/connect/favorite-connections",
    "/connect/favorite-connections/import-export",
    "/indexes",
    "/instance", 
    "/config-file",
    "/query/filter",
    "/query-with-natural-language/query-with-natural-language",
    "/query/queries",
    "/documents", 
    "/schema", 
    "/create-agg-pipeline", 
    "/collections"
]

[constants]
download-page = "`downloads page <https://www.mongodb.com/try/download/compass>`__"
current-version = "1.40.4"
atlas = "MongoDB Atlas"
qe = "Queryable Encryption"
qe-preview = "{+qe+} Public Preview"
qe-equality-ga = "{+qe+} with equality queries"

[[banners]]
targets = [
    "connect/in-use-encryption.txt",
    "in-use-encryption-tutorial.txt",
    "collections/encrypted-collection.txt",
]

variant = "warning"
value = """
    {+qe-equality-ga+} is generally available (GA) in MongoDB 7.0 and \
    later. The {+qe-preview+}, released in version 6.0, is no longer supported. \
    Data encrypted using the Public Preview is incompatible with the feature release. \
    For more information, see :ref:`7.0-compatibility`.
    """

[[banners]]
targets = [
    "query-with-natural-language/enable-natural-language-querying.txt",
    "query-with-natural-language/prompt-natural-language-query.txt",
    "query-with-natural-language/prompt-natural-language-aggregation.txt",
    "query-with-natural-language/query-with-natural-language.txt"
]
variant = "tip"
value = """
    The MongoDB Compass natural language querying feature is currently \
    available as a **Public Preview** offering. The product, its features, \ 
    and the corresponding documentation may change during the Preview stage.
    """

[substitutions]
atlas = "MongoDB Atlas"
compass = "MongoDB Compass"
compass-short = "Compass"
sql = ":abbr:`SQL (Structured Query Language)`"
service = "Atlas"
json = ":abbr:`JSON (Javascript Object Notation)`"
bson = ":abbr:`BSON (Binary Javascript Object Notation)`"
checkmark = "√"
