name = "compass"

[constants]
version = "1.18"
current-version = "1.17.0"
download-page = "`downloads page <https://www.mongodb.com/download-center/compass?jmp=docs>`__"

[substitutions]
branch = "``{0}``'.format(conf.git.branches.current"
copy = "U+000A9"
year = "{0}'.format(datetime.date.today().year"
ent-build = "MongoDB Enterprise"
hardlink = "http://docs.mongodb.com/compass/"
compass = "MongoDB Compass"
compass-short = "Compass"
checkmark = ":icon:`check-circle`"
2fa = ":abbr:`2FA (Two Factor Authentication)`"
api = ":abbr:`API (Application Programming Interface)`"
aws = ":abbr:`AWS (Amazon Web Services)`"
bic-full = ":bic:`MongoDB Connector for BI </>`"
bic-official = "MongoDB Connector for Business Intelligence for Atlas"
bic-short = ":bic:`BI Connector </>`"
bic = "BI Connector for Atlas"
bson = ":abbr:`BSON (Binary Javascript Object Notation)`"
certauth = "Certificate Authority"
cidr = ":abbr:`CIDR (Classless Inter-Domain Routing)`"
cifs = ":abbr:`CIFS (Common Internet File System)`"
Epoch-time = "Timestamp in the number of seconds that have elapsed since the `UNIX epoch <https://en.wikipedia.org/wiki/Unix_time?oldid=828172017>`__"
epoch-time = "timestamp in the number of seconds that have elapsed since the `UNIX epoch <https://en.wikipedia.org/wiki/Unix_time?oldid=828172017>`__"
Epoch-time-ms = "Timestamp in the number of milliseconds that have elapsed since the `UNIX epoch <https://en.wikipedia.org/wiki/Unix_time?oldid=828172017>`__"
epoch-time-ms = "timestamp in the number of milliseconds that have elapsed since the `UNIX epoch <https://en.wikipedia.org/wiki/Unix_time?oldid=828172017>`__"
fqdn = ":abbr:`FQDN (fully qualified domain name)`"
gcp = ":abbr:`GCP (Google Cloud Platform)`"
global-write-clusters = "Global Clusters"
global-write-cluster = "Global Cluster"
global-write = "Global Writes"
https = ":abbr:`HTTPS (Secure HyperText Transport Protocol)`"
http = ":abbr:`HTTP (HyperText Transport Protocol)`"
iana = ":abbr:`IANA (Internet Assigned Numbers Authority)`"
ipaddr = ":abbr:`IP (Internet Protocol)`"
ipv4 = ":abbr:`IPv4 (Internet Protocol version 4)`"
ipv6 = ":abbr:`IPv6 (Internet Protocol version 6)`"
iops = ":abbr:`IOPS (Input/Output Operations per Second)`"
iso8601-duration = "Duration in `ISO 8601 <https://en.wikipedia.org/wiki/ISO_8601?oldid=851138376#Durations>`__ notation"
iso8601-time = "Timestamp in `ISO 8601 <https://en.wikipedia.org/wiki/ISO_8601?oldid=793821205>`__ date and time format in |utc|"
iso8601 = "`ISO 8601 <https://en.wikipedia.org/wiki/ISO_8601?oldid=793821205>`__"
jira = "`Jira <https://jira.mongodb.org>`__""
json = ":abbr:`JSON (Javascript Object Notation)`"
kdc = ":abbr:`KDC (Key Distribution Center)`"
kmip = ":abbr:`KMIP (Key Management Interoperability)`"
kms = ":abbr:`KMS (Key Management Service)`"
ldaps = ":abbr:`LDAPS (Secure Lightweight Directory Access Protocol)`"
ldap = ":abbr:`LDAP (Lightweight Directory Access Protocol)`"
mms-full = "MongoDB Cloud Manager"
mms = "Cloud Manager"
nfs = ":abbr:`NFS (Network File System)`"
piv = ":abbr:`PIV (Personal Identity Verification)`"
rdp = ":abbr:`RDP (Remote Desktop Protocol)`"
restapi = ":abbr:`REST (Representational State Transfer)` :abbr:`API (Application Programming Interface)`"
rest = ":abbr:`REST (Representational State Transfer)`"
s3 = ":abbr:`S3 (Simple Storage Service)`"
service-fullname = "MongoDB Atlas"
service-pricing = "Atlas pricing page"
service = "Atlas"
sms = ":abbr:`SMS (short message service)`"
smtp = ":abbr:`SMTP (Simple Mail Transport Protocol)`"
snmp = ":abbr:`SNMP (Simple Network Management Protocol)`"
spn = ":abbr:`SPN (Service Principal Name)`"
sql = ":abbr:`SQL (Structured Query Language)`"
ssd = ":abbr:`SSD (Solid State Disk)`"
ssl = ":abbr:`SSL (Secure Sockets Layer)`"
stitch-docs = "MongoDB Stitch"
tcp = ":abbr:`TCP (Transmission Control Protocol)`"
tls-ssl = ":abbr:`TLS (Transport Layer Security)`/:abbr:`SSL (Secure Sockets Layer)`"
tls = ":abbr:`TLS (Transport Layer Security)`"
totp = ":abbr:`TOTP (Time-based One-time Password Algorithm)`"
udp = ":abbr:`UDP (User Datagram Protocol)`"
upn = ":abbr:`UPN (User Principal Name)`"
uri = ":abbr:`URI (Uniform Resource Identifier)`"
url = ":abbr:`URL (Uniform Resource Locator)`"
utc = ":abbr:`UTC (Coordinated Universal Time)`"
vpc = ":abbr:`VPC (Virtual Private Cloud)`"
yaml = ":abbr:`YAML (Yet Another Markup Language)`"
