name = "compass"
title = "MongoDB Compass"

intersphinx = ["https://docs.mongodb.com/manual/objects.inv", "https://docs.mongodb.com/database-tools/objects.inv"]

toc_landing_pages = ["/install", "/connect", "/instance", "/query/filter", "/query/queries",
                     "/documents", "/schema", "/aggregation-pipeline-builder"]

[constants]
download-page = "`downloads page <https://www.mongodb.com/download-center/compass?tck=docs_compass>`__"
current-version = "1.26.1-beta.1"
current-version-deb = "1.26.1~beta.1"


[substitutions]
compass = "MongoDB Compass"
compass-short = "Compass"
sql = ":abbr:`SQL (Structured Query Language)`"
service = "Atlas"
json = ":abbr:`JSON (Javascript Object Notation)`"
bson = ":abbr:`BSON (Binary Javascript Object Notation)`"
checkmark = "√"
