name = "compass"
title = "MongoDB Compass"

intersphinx = [
    "https://www.mongodb.com/docs/manual/objects.inv",
    "https://www.mongodb.com/docs/database-tools/objects.inv",
    "https://www.mongodb.com/docs/mongodb-shell/objects.inv",
    "https://www.mongodb.com/docs/atlas/objects.inv"
]

toc_landing_pages = [
    "/install", 
    "/connect",
    "/settings",
    "/settings/config-file",
    "/connect/advanced-connection-options",
    "/connect/favorite-connections",
    "/connect/favorite-connections/import-export",
    "/instance", 
    "/config-file",
    "/query/filter",
    "/query-with-natural-language/query-with-natural-language",
    "/query/queries",
    "/documents", 
    "/schema", 
    "/create-agg-pipeline", 
    "/collections"
]

[constants]
download-page = "`downloads page <https://www.mongodb.com/try/download/compass>`__"
current-version = "1.40.0"
atlas = "MongoDB Atlas"

[[banners]]
targets = [
    "connect/in-use-encryption.txt",
    "in-use-encryption-tutorial.txt",
    "collections/encrypted-collection.txt",
]

variant = "danger"
value = """
    Queryable Encryption is in Public Preview and available for \
    evaluation purposes. Public Preview is not recommended for \
    production deployments as breaking changes may be introduced. \
    To learn more about the Preview please see the \
    `Queryable Encryption Preview <https://www.mongodb.com/blog/post/mongodb-releases-queryable-encryption-preview/>`__ \
    blog post.
    """

[[banners]]
targets = [
    "query-with-natural-language/enable-natural-language-querying.txt",
    "query-with-natural-language/prompt-natural-language-query.txt",
    "query-with-natural-language/prompt-natural-language-aggregation.txt",
    "query-with-natural-language/query-with-natural-language.txt"
]
variant = "tip"
value = """
    The MongoDB Compass natural language querying feature is currently \
    available as a **Public Preview** offering. The product, its features, \ 
    and the corresponding documentation may change during the Preview stage. \
    This feature is on a rolling release schedule. As a result, some \
    users may temporarily have functionality \
    that other users do not. \
    """

[substitutions]
atlas = "MongoDB Atlas"
compass = "MongoDB Compass"
compass-short = "Compass"
sql = ":abbr:`SQL (Structured Query Language)`"
service = "Atlas"
json = ":abbr:`JSON (Javascript Object Notation)`"
bson = ":abbr:`BSON (Binary Javascript Object Notation)`"
checkmark = "√"
