name = "compass"
title = "MongoDB Compass"

intersphinx = [
    "https://www.mongodb.com/docs/manual/objects.inv",
    "https://www.mongodb.com/docs/database-tools/objects.inv",
    "https://www.mongodb.com/docs/mongodb-shell/objects.inv"
]

toc_landing_pages = ["/install", "/connect", "/instance", "/query/filter", "/query/queries",
                     "/documents", "/schema", "/aggregation-pipeline-builder"]

[constants]
download-page = "`downloads page <https://www.mongodb.com/download-center/compass?tck=docs_compass>`__"
current-version = "1.31.3"


[substitutions]
compass = "MongoDB Compass"
compass-short = "Compass"
sql = ":abbr:`SQL (Structured Query Language)`"
service = "Atlas"
json = ":abbr:`JSON (Javascript Object Notation)`"
bson = ":abbr:`BSON (Binary Javascript Object Notation)`"
checkmark = "√"
