name = "compass"
title = "MongoDB Compass"

intersphinx = [
    "https://www.mongodb.com/docs/manual/objects.inv",
    "https://www.mongodb.com/docs/database-tools/objects.inv",
    "https://www.mongodb.com/docs/mongodb-shell/objects.inv"
]

toc_landing_pages = [
    "/install", 
    "/connect",
    "/settings",
    "/settings/config-file",
    "/connect/advanced-connection-options",
    "/connect/favorite-connections",
    "/connect/favorite-connections/import-export",
    "/instance", 
    "/config-file",
    "/query/filter", 
    "/query/queries",
    "/documents", 
    "/schema", 
    "/aggregation-pipeline-builder", 
    "/collections"
]

[constants]
download-page = "`downloads page <https://www.mongodb.com/try/download/compass>`__"
current-version = "1.39.0"

[[banners]]
targets = [
    "connect/in-use-encryption.txt",
    "in-use-encryption-tutorial.txt",
    "collections/encrypted-collection.txt",
]

variant = "danger"
value = """
    Queryable Encryption is in Public Preview and available for \
    evaluation purposes. Public Preview is not recommended for \
    production deployments as breaking changes may be introduced. \
    To learn more about the Preview please see the \
    `Queryable Encryption Preview <https://www.mongodb.com/blog/post/mongodb-releases-queryable-encryption-preview/>`__ \
    blog post.
    """

[substitutions]
compass = "MongoDB Compass"
compass-short = "Compass"
sql = ":abbr:`SQL (Structured Query Language)`"
service = "Atlas"
json = ":abbr:`JSON (Javascript Object Notation)`"
bson = ":abbr:`BSON (Binary Javascript Object Notation)`"
checkmark = "√"
